
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Luke",
  "lastName": "Skywalker",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Anikin",
  "lastName": "Skywalker",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Han",
  "lastName": "Solo",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Kylo",
  "lastName": "Ren",
  "phoneNumber": "111-111-1112"

}
###


# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Daenerys",
  "lastName": "Targaryen",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Sansa",
  "lastName": "Stark",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "Arya",
  "lastName": "Stark",
  "phoneNumber": "111-111-1112"

}
###

# curl -i -X POST -d "{"firstName": "Frodo","lastName": "Baggins",  "phoneNumber": "111-111-1112"}"
#  -H "Content-Type:application/json" http://localhost:8080/buddy
POST http://localhost:8080/buddy
Content-Type: application/json

{"firstName": "John",
  "lastName": "Snow",
  "phoneNumber": "111-111-1112"

}
###


# curl -i -X POST "
#  -H "Content-Type:application/json" http://localhost:8080/addressBook
POST http://localhost:8080/addressBook
Content-Type: application/json

{
}

###



//Adding buddies to the addressBook

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/1/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/2

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/1/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/3

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/1/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/4

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/1/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/5

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/14/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/6

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/14/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/7

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/12/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/8

###


# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/12/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/9

###



# curl -i -X PUT -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
DELETE http://localhost:8080/addressBook/12/addressBook
Content-Type: text/uri-list
http://localhost:8080/buddy/9

###


# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
POST http://localhost:8080/addressBook/12/addressBook
Content-Type: text/uri-list

http://localhost:8080/buddy/6

<> 2021-02-05T122118.409.json

###

# curl -i -X POST -d "http://localhost:8080/buddy/1"
#  -H "Content-Type:text/uri-list" http://localhost:8080/addressBook/1/addressBook
#DELETE http://localhost:8080/addressBook/14/addressBook
#Content-Type: text/uri-list
#
#http://localhost:8080/buddy/6



## curl -i -X DELETE http://localhost:8080/addressBook/1/addressBook
#DELETE http://localhost:8080/addressBook/14/addressBook/6




